builds:
  - binary: ipmi_exporter
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser
      - -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      - -X github.com/prometheus/common/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
      - ppc64
      - ppc64le
    goarm:
      - "6"
      - "7"
archives:
  - name_template: "ipmi_exporter-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
checksum:
  name_template: checksums.txt
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}/ipmi-exporter:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}/ipmi-exporter:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}/ipmi-exporter:{{ .Version }}-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}/ipmi-exporter:latest-arm64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--platform=linux/arm64"
    goarch: arm64
docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}/ipmi-exporter:{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}/ipmi-exporter:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}/ipmi-exporter:{{ .Version }}-arm64"
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}/ipmi-exporter:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}/ipmi-exporter:latest"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}/ipmi-exporter:latest-arm64"
nfpms:
  - homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}/{{ .ProjectName }}
    maintainer: prometheus-developers@googlegroups.com
    description: Prometheus exporter for IPMI metrics
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: packaging/ipmi-exporter.service
        dst: /lib/systemd/system/ipmi-exporter.service
      - src: packaging/conf/ipmi-local.yml
        dst: /etc/ipmi-exporter/ipmi-local.yml
        type: config
      - src: packaging/default/ipmi-exporter
        dst: /etc/default/ipmi-exporter
        type: config
    scripts:
      postinstall: "packaging/scripts/postinstall.sh"
      postremove: "packaging/scripts/postremove.sh"
      preremove: "packaging/scripts/preremove.sh"
release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER | default 'monitoring-projects' }}"
    name: "{{ .ProjectName }}"
  draft: false
  prerelease: auto
